import type { AdSpec } from "../engine/types";

export const adSpec = {
  id: "form-01",
  name: "FORM 01 · Quiet by design",
  fontFamily: "Arial, sans-serif",
  colors: {
    background: "#f5e55b",
    foreground: "#24291e",
    action: "#24291e",
    actionText: "#fffde8",
  },
  elements: [
    {
      id: "brand",
      type: "text",
      role: "branding",
      priority: 3,
      optional: true,
      text: "FORM®",
      constraints: { idealWidth: 112, minWidth: 72 },
      typography: {
        idealFontSize: 26,
        minFontSize: 18,
        lineHeight: 1.15,
        weight: 700,
        maxLines: 1,
      },
    },
    {
      id: "headline",
      type: "text",
      role: "primary",
      priority: 1,
      optional: false,
      text: "Less noise.\nMore feeling.",
      constraints: { idealWidth: 350, minWidth: 118 },
      typography: {
        idealFontSize: 58,
        minFontSize: 24,
        lineHeight: 1.08,
        weight: 700,
        maxLines: 4,
      },
    },
    {
      id: "hero",
      type: "image",
      role: "hero",
      priority: 1,
      optional: false,
      src: "/headphones.png",
      alt: "Ivory FORM 01 over-ear headphones with brushed silver hinges",
      constraints: { idealWidth: 300, minWidth: 76 },
      idealHeight: 300,
      minHeight: 76,
    },
    {
      id: "price",
      type: "text",
      role: "secondary",
      priority: 2,
      optional: true,
      text: "FORM 01 / $249",
      constraints: { idealWidth: 170, minWidth: 95 },
      typography: {
        idealFontSize: 19,
        minFontSize: 14,
        lineHeight: 1.3,
        weight: 500,
        maxLines: 2,
      },
    },
    {
      id: "cta",
      type: "button",
      role: "action",
      priority: 1,
      optional: false,
      text: "Explore FORM 01",
      href: "#product-details",
      constraints: { idealWidth: 206, minWidth: 110 },
      minHeight: 48,
      typography: {
        idealFontSize: 17,
        minFontSize: 16,
        lineHeight: 1.25,
        weight: 600,
        maxLines: 2,
      },
    },
  ],
} satisfies AdSpec;
