import type { SurfaceProfile } from "../engine/types";

export const surfaces: readonly SurfaceProfile[] = [
  {
    id: "portrait",
    name: "Mobile Portrait",
    width: 390,
    height: 844,
    safeArea: { top: 44, right: 0, bottom: 34, left: 0 },
    padding: 24,
    gap: 20,
    minTapTarget: 44,
    minTextSize: 14,
    viewingDistance: 0.4,
    touchOnly: true,
  },
  {
    id: "landscape",
    name: "Mobile Landscape",
    width: 844,
    height: 390,
    safeArea: { top: 0, right: 44, bottom: 21, left: 44 },
    padding: 22,
    gap: 16,
    minTapTarget: 44,
    minTextSize: 14,
    viewingDistance: 0.4,
    touchOnly: true,
  },
  {
    id: "broadcast",
    name: "Broadcast Lower Third",
    width: 1920,
    height: 240,
    safeArea: { top: 12, right: 96, bottom: 24, left: 96 },
    padding: 20,
    gap: 24,
    minTapTarget: 0,
    minTextSize: 28,
    viewingDistance: 3,
    touchOnly: false,
  },
  {
    id: "kiosk",
    name: "Square Retail Kiosk",
    width: 800,
    height: 800,
    safeArea: { top: 24, right: 24, bottom: 24, left: 24 },
    padding: 36,
    gap: 24,
    minTapTarget: 60,
    minTextSize: 20,
    viewingDistance: 0.8,
    touchOnly: true,
  },
];

export const customPresets: readonly SurfaceProfile[] = [
  {
    id: "custom-signage",
    name: "Portrait signage",
    width: 720,
    height: 1280,
    safeArea: { top: 24, right: 24, bottom: 24, left: 24 },
    padding: 24,
    gap: 24,
    minTapTarget: 0,
    minTextSize: 28,
    viewingDistance: 2,
    touchOnly: false,
  },
  {
    id: "custom-strip",
    name: "Ultra-wide strip",
    width: 1600,
    height: 180,
    safeArea: { top: 8, right: 24, bottom: 8, left: 24 },
    padding: 12,
    gap: 16,
    minTapTarget: 0,
    minTextSize: 24,
    viewingDistance: 2,
    touchOnly: false,
  },
  {
    id: "custom-card",
    name: "Compact card",
    width: 320,
    height: 320,
    safeArea: { top: 8, right: 8, bottom: 8, left: 8 },
    padding: 12,
    gap: 10,
    minTapTarget: 44,
    minTextSize: 14,
    viewingDistance: 0.4,
    touchOnly: true,
  },
];
